apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetcore-deployment
  labels:
    app: dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-container
        image: nelson6r/webapplication20
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app
spec:
  selector:
    app: dotnet-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort